// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("KNXLib")]
[assembly: AssemblyProductAttribute("KNX.net")]
[assembly: AssemblyDescriptionAttribute("KNX.net provides a KNX API for .NET")]
[assembly: AssemblyVersionAttribute("1.0.2")]
[assembly: AssemblyFileVersionAttribute("1.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.2";
    }
}
